export const GET_ANIMES_REQUEST = 'GET_ANIMES_REQUEST'
export const GET_ANIMES_SUCCESS = 'GET_ANIMES_SUCCESS'
export const GET_ANIMES_FAILURE = 'GET_ANIMES_FAILURE'


export const GET_ANIME_REQUEST = 'GET_ANIME_REQUEST'
export const GET_ANIME_SUCCESS = 'GET_ANIME_SUCCESS'
export const GET_ANIME_FAILURE = 'GET_ANIME_FAILURE'